using System;

namespace Diga.Core.Api.Win32.Com.ActiveScript
{
    [Flags]
    public enum SCRIPTTEXT : uint
    {
        SCRIPTTEXT_DELAYEXECUTION = 0x00000001,
        SCRIPTTEXT_ISVISIBLE = 0x00000002,
        SCRIPTTEXT_ISEXPRESSION = 0x00000020,
        SCRIPTTEXT_ISPERSISTENT = 0x00000040,
        SCRIPTTEXT_HOSTMANAGESSOURCE = 0x00000080,
        SCRIPTTEXT_ISXDOMAIN = 0x00000100,
        SCRIPTTEXT_ISNONUSERCODE = 0x00000200,
        SCRIPTTEXT_ALL_FLAGS = (SCRIPTTEXT_DELAYEXECUTION | SCRIPTTEXT_ISVISIBLE | SCRIPTTEXT_ISEXPRESSION | SCRIPTTEXT_ISPERSISTENT | SCRIPTTEXT_HOSTMANAGESSOURCE | SCRIPTTEXT_ISXDOMAIN | SCRIPTTEXT_ISNONUSERCODE)
    }
}