namespace Diga.Core.Api.Win32.Dwm
{
    public enum DWM_TAB_WINDOW_REQUIREMENTS
    {

        /// DWMTWR_NONE -> 0x0000
        DWMTWR_NONE = 0,

        /// DWMTWR_IMPLEMENTED_BY_SYSTEM -> 0x0001
        DWMTWR_IMPLEMENTED_BY_SYSTEM = 1,

        /// DWMTWR_WINDOW_RELATIONSHIP -> 0x0002
        DWMTWR_WINDOW_RELATIONSHIP = 2,

        /// DWMTWR_WINDOW_STYLES -> 0x0004
        DWMTWR_WINDOW_STYLES = 4,

        /// DWMTWR_WINDOW_REGION -> 0x0008
        DWMTWR_WINDOW_REGION = 8,

        /// DWMTWR_WINDOW_DWM_ATTRIBUTES -> 0x0010
        DWMTWR_WINDOW_DWM_ATTRIBUTES = 16,

        /// DWMTWR_WINDOW_MARGINS -> 0x0020
        DWMTWR_WINDOW_MARGINS = 32,

        /// DWMTWR_TABBING_ENABLED -> 0x0040
        DWMTWR_TABBING_ENABLED = 64,

        /// DWMTWR_USER_POLICY -> 0x0080
        DWMTWR_USER_POLICY = 128,

        /// DWMTWR_GROUP_POLICY -> 0x0100
        DWMTWR_GROUP_POLICY = 256,

        /// DWMTWR_APP_COMPAT -> 0x0200
        DWMTWR_APP_COMPAT = 512,
    }
}