namespace Diga.Core.Api.Win32.Dwm
{
    public enum DWMTRANSITION_OWNEDWINDOW_TARGET
    {

        /// DWMTRANSITION_OWNEDWINDOW_NULL -> -1
        DWMTRANSITION_OWNEDWINDOW_NULL = -1,

        /// DWMTRANSITION_OWNEDWINDOW_REPOSITION -> 0
        DWMTRANSITION_OWNEDWINDOW_REPOSITION = 0,
    }
}